version: '3'
services:
    travertine:
        build: images/travertine
        ports:
            - 25565:25577
        networks:
            - local

    lobby:
        build: images/lobby
        environment:
            - SERVER_NAME=lobby-01
            - SERVER_GROUP=lobby
            - SERVER_CATEGORY=lobby
        networks:
            - local
        volumes:
            - /mnt/data/maps/lobby:/server/world

networks:
    local:

