version: '3'
services:
    travertine:
        build: images/travertine
        ports:
            - 25565:25577
        links:
            - lobby
            - mixed-01

    lobby:
        build: images/lobby
        environment:
            - SERVER_NAME=lobby-01
            - SERVER_GROUP=lobby
            - SERVER_CATEGORY=lobby
        volumes:
            - /mnt/data/maps/lobby:/server/world
            - /mnt/data/WorldEdit/worldedit-bukkit/build/libs/worldedit-bukkit-7.3.0-SNAPSHOT-dist.jar:/server/plugins/worldedit.jar

    mixed-01:
        build: images/mixed
        volumes:
            - /mnt/data/WorldEdit/worldedit-bukkit/build/libs/worldedit-bukkit-7.3.0-SNAPSHOT-dist.jar:/server/plugins/worldedit.jar
