version: '3'
services:
    bungeecord:
        image: itzg/bungeecord
        environment:
            - UID=1000
        ports:
            - 25565:25577
        volumes:
            - /mnt/data/plugins/DockerizedCraft.jar:/server/plugins/DockerizedCraft.jar
            - ~/infrastructure/setup/craft/configs/DockerizedCraft:/server/plugins/DockerizedCraft
            - //var/run/docker.sock:/var/run/docker.sock
        networks:
            - local

    redis:
        image: bitnami/redis:latest
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        networks:
            - local

    lobby-01:
        image: lobby
        environment:
            - SERVER_NAME=lobby-01
            - SERVER_GROUP=lobby
            - SERVER_CATEGORY=lobby
        networks:
            - local
        volumes:
            - /mnt/data/maps/lobby:/server/world

networks:
    local:

