server_connect_timeout: 5000
listeners:
- query_port: 25577
  motd: p
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
      pgm.retarders.top: mixed
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 420
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: false
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: false
groups:
  pcranaway:
  - admin
remote_ping_timeout: 5000
connection_throttle: 1000
log_commands: false
stats: b315263f-672b-4208-b44b-1ba7de1b6001
online_mode: true
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: p
    address: lobby_1:25565
    restricted: false
